### PR TITLE
Added Documentation and Example for Design Systems

### PR DESCRIPTION
**Pull request by taher-pro**
1. Updated name of the project in documentation to `create-drupal-theme`
2. Added commits from Swarads branch, I am not able to bring forward changes without rewriting the history so I am adding this as a replacement PR for https://github.com/axelerant/kashmir/pull/240

### CODE REVIEW

**Comment by swarad07** [comment]
Can you elaborate on why we need a new PR? 

Since we are already reviewing things in the other PR, we will lose the history in this duplicate one.

**Comment by taher-pro** [comment]
@swarad07 I created this PR as I could not create a PR against your branch yesterday after rebasing my local with the latest v2. Can you rebase that branch in your forked repo so I can make a PR against it and then close this PR?

**Comment by swarad07** [comment]
Sure doing.

**Comment by swarad07** [comment]
Check now, my branch is updated with latest v2.

**Comment by taher-pro** [comment]
@swarad07 Please review https://github.com/swarad07/kashmir/pull/2 I am closing this now. Thanks!

**Pull request closed without merging**
